<a href="https://colab.research.google.com/github/vishnu43/NeuralNet2/blob/main/Neural_Networks_and_Deep_Learning_ICP_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
class Employee:
    numberOfEmployees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.numberOfEmployees+=1


def averagesalary(employee):
    total = sum(e.salary for e in employee)
    average = total / len(employee)
    return average

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        Employee.__init__(self,name, family, salary, department)

print("Employee 1: ")
employee1 = Employee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("Employee 2: ")
employee2 = Employee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("Full Time Employee 1: ")
employee3 = FulltimeEmployee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("")
print("Number of employees: ",Employee.numberOfEmployees)
listofEmployees = [employee1, employee2]
avgsalary = averagesalary(listofEmployees)
print("Avg salary is :", avgsalary)

Employee 1: 
Enter name: Vish
Family Members: 3
Employee Salary: 50000
Employee Department: Finance
Employee 2: 
Enter name: Rakesh
Family Members: 2
Employee Salary: 60000
Employee Department: HR
Full Time Employee 1: 
Enter name: Abhi
Family Members: 5
Employee Salary: 70000
Employee Department: Food

Number of employees:  3
Avg salary is : 55000.0


In [7]:
import numpy

random_vector = numpy.random.uniform(1, 20, 20)
print(random_vector)
print("")
print("")
reshaped_array = random_vector.reshape(4, 5)
print("")
print("")
print(reshaped_array)
reshaped_array[numpy.arange(4), numpy.argmax(reshaped_array, axis=1)] = 0
print("")
print("")
print(reshaped_array)

[19.21717659 12.92172739 13.97070614 17.06286965 10.28504239 11.94591653
  7.76806016  3.34136888  1.01055929  2.52202219 13.9371019  16.36242411
 16.70563534  8.48336104  4.48700438  4.53948231 17.18913367 14.89428355
  8.49958249  2.80539356]




[[19.21717659 12.92172739 13.97070614 17.06286965 10.28504239]
 [11.94591653  7.76806016  3.34136888  1.01055929  2.52202219]
 [13.9371019  16.36242411 16.70563534  8.48336104  4.48700438]
 [ 4.53948231 17.18913367 14.89428355  8.49958249  2.80539356]]


[[ 0.         12.92172739 13.97070614 17.06286965 10.28504239]
 [ 0.          7.76806016  3.34136888  1.01055929  2.52202219]
 [13.9371019  16.36242411  0.          8.48336104  4.48700438]
 [ 4.53948231  0.         14.89428355  8.49958249  2.80539356]]
